name: Random GIF in README

permissions:
  contents: write

on:
  schedule:
    - cron: "*/10 * * * *"

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Pick a random GIF
      id: random
      run: |
        FILE=$(ls gifs | shuf -n 1)
        echo "random_gif=gifs/$FILE" >> $GITHUB_ENV

    - name: Update README
      run: |
        sed -i 's|<img src="[^"]*" width="300">|<img src="'${{ env.random_gif }}'" width="300">|' README.md

    - name: Commit changes
      run: |
        git config user.name "github-actions"
        git config user.email "actions@github.com"
        git add README.md
        git commit -m "update random GIF" || exit 0
        git push
